// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import ControleEditoraService from '../controle-editora.service';
import ControleLivrosService, { LivroMongo } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-livro-lista',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css',
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<LivroMongo> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((livros) => {
      this.livros = livros;
    })
  }

  excluir = (codigo: String): void => {
    this.servLivros.excluir(codigo)
    .then(() => {
      this.servLivros.obterLivros().then((livros) => {
        this.livros = livros;
      })
    })
  };

  obterNome = (codEditora: number): string | undefined => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}

<!-- <div class="container mt-5"> -->
<main style="width: 70%; margin-inline: auto; margin-top: 1rem">
  <h1 class="text-center mb-4">Catálogo de Livros</h1>
  <table class="table table-striped">
    <thead class="table-dark">
      <tr>
        <th style="width: '16%'">Título</th>
        <th style="width: '50%'">Resumo</th>
        <th style="width: '16%'">Editora</th>
        <th style="width: '16%'">Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>
          <h6>{{ livro.titulo }}</h6>
          <button
            class="btn btn-danger"
            (click)="excluir(livro._id ?? '')"
          >
            Excluir
          </button>
        </td>
        <td>{{ livro.resumo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</main>
<!-- </div> -->

// clientes/livros-react/src/LivroLista.js
import { useEffect, useState } from "react";
import ControleEditora from "./controle/ControleEditora";
import ControleLivro from "./controle/ControleLivros";
import style from './LivroLista.module.css'

const LinhaLivro = ({ livro, excluir, index }) => {
  const controleEditora = new ControleEditora();
  const nomeEditora = controleEditora.getNomeEditora(livro.codEditora)
  return (
    <>
        <tr>
            <td>
              <h6>{livro.titulo}</h6>
              <button class="btn btn-danger" onClick={() => excluir(livro._id)}>Excluir</button>

            </td>
            <td>{livro.resumo}</td>
            <td>{nomeEditora}</td>
            <td>
              <ul>
                {livro.autores.map((autor) => <li>{autor}</li>)}
              </ul>
            </td>
            
        </tr>
    </>
  )
}

const LivroLista = () => {
  const [livros, setLivros] = useState([])
  const [carregado, setCarregado] = useState(false)
  const controleLivro = new ControleLivro();

  useEffect(() => {
    controleLivro.obterLivros().then((livrosObtidos) => {
      setLivros(livrosObtidos);
      setCarregado(true);
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[carregado])

  const excluir = async (codigo) => {
    await controleLivro.excluir(codigo)
    setCarregado(false)
  }

  return (
    <>
    <main>
      <h1>Catálogo de Livros</h1>
      <table class={style.tabela} className="table table-striped table-hover">
        <thead class="table-dark">
          <tr>
            <th style={{ width: '16%' }}>Título</th>
            <th style={{ width: '50%' }}>Resumo</th>
            <th style={{ width: '16%' }}>Editora</th>
            <th style={{ width: '16%' }}>Autores</th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro, index) => 
            <LinhaLivro key={livro.titulo} livro={livro} excluir={excluir} index={index} />
          )}
        </tbody>
      </table>
    </main>
    </>
  )
}

export default LivroLista;
